---
title: "Hypergraph Centrality"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: flatly
---

```{r setup, include=FALSE}
library(flexdashboard)
library(highcharter)
library(psych)
load("/Users/hugh/Documents/University/Maths/Year4/Project/RCode/CentralityCode/Data/Betweenness.RData")
```

Coding
==========

Row {data-height=800}
----------
```{r, dpi=240}
knitr::include_url("codemarkdown.html", height = "800px")
```

Hype BC vs Graph BC
==========

Row {data-height=500}
----------

### **Active and Passive Members** {data-width=800}

```{r}
cutoff.hype <- quantile(bc.data$hall, 0.8)
cutoff.graph <- quantile(bc.data$graph, 0.8)

bc.data$class <- ((bc.data$hall > cutoff.hype) == (bc.data$graph > cutoff.graph))

x <- c("Protein", "Graph BC:", "Hype (All) BC:", "Agreement")
y <- sprintf("{point.%s:.2f}", c("protein", "graph", "hall", "class"))
tltip <- tooltip_table(x,y)

bc.data %>%
  hchart("point", hcaes(x = graph, y = hall, group = class)) %>%
  hc_colors(c("red", "lime")) %>%
  hc_xAxis(title = list(text = "Graph Betweenness Centrality")) %>%
  hc_yAxis(title = list(text = "Hypergraph Betweenness Centrality - Active and Non-Terminating Passive Members")) %>%
  hc_tooltip(useHTML = TRUE, headerFormat = "", pointFormat = tltip)
```

### **Active and Passive Members**

Lorem Ipsum yada yada yada

Row
----------

### Pearson's Moment Correlation Coefficient
```{r}
gauge(round(cor(bc.data$graph, bc.data$hall), digits = 2),
  min = 0,
  max = 1,
  gaugeSectors(danger = c(0, 0.7),
               warning = c(0.7, 0.9),
               success = c(0.9, 1)
               )
)
```

### Class Agreement

```{r}
gauge(round(length(which(bc.data$class))/length(bc.data$class), digits = 2),
  min = 0,
  max = 1,
  gaugeSectors(danger = c(0, 0.7),
               warning = c(0.7, 0.9),
               success = c(0.9, 1)
               )
)
```


Row {data-height=500}
----------

### **Active and Non-Terminating Passive Members** {data-width=800}

```{r}
cutoff.hype <- quantile(bc.data$hnt, 0.8)
cutoff.graph <- quantile(bc.data$graph, 0.8)

bc.data$class <- ((bc.data$hnt > cutoff.hype) == (bc.data$graph > cutoff.graph))

x <- c("Protein", "Graph BC:", "Hype (NT) BC:", "Agreement")
y <- sprintf("{point.%s:.2f}", c("protein", "graph", "hnt", "class"))
tltip <- tooltip_table(x,y)

bc.data %>%
  hchart("point", hcaes(x = graph, y = hnt, group = class)) %>%
  hc_colors(c("red", "lime")) %>%
  hc_xAxis(title = list(text = "Graph Betweenness Centrality")) %>%
  hc_yAxis(title = list(text = "Hypergraph Betweenness Centrality - Active and Non-Terminating Passive Members")) %>%
  hc_tooltip(useHTML = TRUE, headerFormat = "", pointFormat = tltip)
```

### **Active and Non-Terminating Passive Members**

Lorem Ipsum yada yada yada

Row
----------

### Pearson's Moment Correlation Coefficient
```{r}
gauge(round(cor(bc.data$graph, bc.data$hnt), digits = 2),
  min = 0,
  max = 1,
  gaugeSectors(danger = c(0, 0.7),
               warning = c(0.7, 0.9),
               success = c(0.9, 1)
               )
)
```

### Class Agreement

```{r}
gauge(round(length(which(bc.data$class))/length(bc.data$class), digits = 2),
  min = 0,
  max = 1,
  gaugeSectors(danger = c(0, 0.7),
               warning = c(0.7, 0.9),
               success = c(0.9, 1)
               )
)
```


Row {data-height=500}
----------

### **Active Members** {data-width=800}

```{r}
cutoff.hype <- quantile(bc.data$hact, 0.8)
cutoff.graph <- quantile(bc.data$graph, 0.8)

bc.data$class <- ((bc.data$hact > cutoff.hype) == (bc.data$graph > cutoff.graph))

x <- c("Protein", "Graph BC:", "Hype (Act) BC:", "Agreement")
y <- sprintf("{point.%s:.2f}", c("protein", "graph", "hact", "class"))
tltip <- tooltip_table(x,y)

bc.data %>%
  hchart("point", hcaes(x = graph, y = hact, group = class)) %>%
  hc_colors(c("red", "lime")) %>%
  hc_xAxis(title = list(text = "Graph Betweenness Centrality")) %>%
  hc_yAxis(title = list(text = "Hypergraph Betweenness Centrality - Active Members")) %>%
  hc_tooltip(useHTML = TRUE, headerFormat = "", pointFormat = tltip)
```

### **Active Members**

Lorem Ipsum yada yada yada

Row
----------

### Pearson's Moment Correlation Coefficient
```{r}
gauge(round(cor(bc.data$graph, bc.data$hact), digits = 2),
  min = 0,
  max = 1,
  gaugeSectors(danger = c(0, 0.7),
               warning = c(0.7, 0.9),
               success = c(0.9, 1)
               )
)
```

### Class Agreement

```{r}
gauge(round(length(which(bc.data$class))/length(bc.data$class), digits = 2),
  min = 0,
  max = 1,
  gaugeSectors(danger = c(0, 0.7),
               warning = c(0.7, 0.9),
               success = c(0.9, 1)
               )
)
```


Hype Deg vs Graph Deg
==========

Row
----------

```{r}

cutoff.hype <- quantile(bc.data$ncomp, 0.8)
cutoff.graph <- quantile(bc.data$gdeg, 0.8)

bc.data$class <- ((bc.data$ncomp > cutoff.hype) == (bc.data$gdeg > cutoff.graph))

x <- c("Protein", "Graph Deg:", "Hype Deg:", "Agreement")
y <- sprintf("{point.%s:.2f}", c("protein", "gdeg", "ncomp", "class"))
tltip <- tooltip_table(x,y)

bc.data %>%
  hchart("point", hcaes(x = gdeg, y = ncomp, group = class)) %>%
  hc_colors(c("red", "lime")) %>%
  hc_tooltip(useHTML = TRUE, headerFormat = "", pointFormat = tltip)
```


